### ISSUE TITLE
Importing Globals is not working

### ISSUE THREAD

**Issue by psteiwer** [intersystems-community/dc-analytics#21]
Here is my terminal output while trying to follow configuration instructions:

DCANALYTICS>do ##class(Community.Utils).setup("C:\Users\psteiwer\Downloads\DCAnalytics_globals_01.Mar.2020")
Enabling iKnow
Building indices
Built Community.Comment with return code = 1
Built Community.Group with return code = 1
Built Community.GroupPost with return code = 1
Built Community.Member with return code = 1
Built Community.Post with return code = 1
Built Community.iKnow.Similar with return code = 1
Built History.ActiveMembers with return code = 1
Built History.AvgComments with return code = 1
Built History.AvgPosts with return code = 1
Built History.ChampionshipPositions with return code = 1
Built History.Views with return code = 1
Building cubes
 
Building cube [CHAMPPOS]
Existing cube deleted.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.018146s
Source expression time:        0.000000s
 
Building cube [COMMENT]
Existing cube deleted.
No source data found.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.021573s
Source expression time:        0.000000s
 
Building cube [COMMENTCOPY]
Existing cube deleted.
No source data found.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.020143s
Source expression time:        0.000000s
 
Building cube [MEMBER]
Existing cube deleted.
No source data found.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.011363s
Source expression time:        0.000000s
 
Building cube [POST]
Existing cube deleted.
No source data found.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.013848s
Source expression time:        0.000000s
 
Building cube [VIEWSHISTORY]
Existing cube deleted.
No source data found.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.020582s
Source expression time:        0.000000s
 
Building cube [VIEWSHISTORYCOPY]
Existing cube deleted.
No source data found.
Fact table built:                 0 fact(s) (4 core(s) used)
Fact indices built:               0 fact(s) (4 core(s) used)
 
Complete
Elapsed time:                  0.020349s
Source expression time:        0.000000s
Done!

**Comment by evshvarov** [comment]
Fixed
