### ISSUE TITLE
link to atscal live demo seems to be wrong

### ISSUE THREAD

**Issue by dkutac** [intersystems-community/dc-analytics#35]
![image](https://user-images.githubusercontent.com/10270607/191249067-bd555cc3-2899-4390-b3c4-3ccfefc826b2.png)

try to click the "Instance of Adaptive Analytics ..." link, it won't work

**Comment by jakcpto** [comment]
> ![image](https://user-images.githubusercontent.com/10270607/191249067-bd555cc3-2899-4390-b3c4-3ccfefc826b2.png)
> 
> try to click the "Instance of Adaptive Analytics ..." link, it won't work

It works for me.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/41373877/191254078-720700ed-3dcb-413b-8d3e-b64b3474d1ee.png">

**Comment by jakcpto** [comment]
Can you ping atscale-public.demo.community.intersystems.com ?

**Comment by dkutac** [comment]
interesting, it works now. When I create the issue, it showed me some malformed URL. but as my PC has also some other issues, I just rebooted it and now the link works just fine.
