### ISSUE TITLE
Why do we need community.inc

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/dc-analytics#4]
https://github.com/intersystems-community/dc-analytics/blob/master/src/inc/Community.inc

What's the purpose?

**Comment by eduard93** [comment]
For macroes?

**Comment by evshvarov** [comment]
Sure. But check the content of the file. Where Server and Pool global is being used?

**Comment by eduard93** [comment]
i.e https://github.com/intersystems-community/dc-analytics/blob/master/src/cls/Community/Post.cls#L34

**Comment by eduard93** [comment]
We don't need pool macro, but server one is used throughout.

**Comment by MakarovS96** [comment]
Ok. Then I delete dependencies and file itself.
