### ISSUE TITLE
Weekly report fixes

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/dc-analytics#6]
Weekly Report -> Developer Community Weekly Report
Period: [Period]
Posts by Members.... 

Weekly Posts -> Posts Daily
Weekly Comments -> Comments Daily
Weekly Comments pivot is absent?

Totals on the right: align by left, not by center.  It's everywhere.

Introduce Articles and Announcements of the week:
Title: Articles and Announcements
The list of clickable articles with Authors (like articledigest)
Totals: 
Articles this week:
Articles average:
Performance:

Introduce Questions of the week block:
Title: Questions This Week
The list of clickable questions with authors (like articledigest)
Totals: 
Questions this week:
Questions average:
Performance:

**Comment by MakarovS96** [comment]
Done
